video: fix build failed Yocto build
1. rename maine.c to main.cc because it uses c++ header files.
2. fix the following error
 /usr/include/bits/fcntl2.h:50:31: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
| 50 | __open_missing_mode ();

Signed-off-by: Jamin Lin <jamin_lin@aspeedtech.com>
Change-Id: I4ed7053e7b8d0245d3636dc64c4640e5a31420eb